### PR TITLE
Codebase refactoring

### PR DESCRIPTION
**Pull request by drillskibo**
This PR will close [#41](https://github.com/PopperDevs/PopperBot/issues/41) refactoring the whole codebase and preparing the bot to be published to its LTS version 1.

### CODE REVIEW

**Comment by drillskibo** [comment]
🚧 The work is still in progress.

**Comment by johanneslosch** [comment]
I think we could close this PR due to inactivity

**Comment by Steffan153** [comment]
It looks like he's still working on this, just busy or smt

**Comment by johanneslosch** [comment]
> It looks like he's still working on this, just busy or smt

I mean it's since opening about 3 month.

**Comment by johanneslosch** [comment]
Closed due to inactivity

**Pull request closed without merging**
