### PR TITLE
Port math command

### LINKED ISSUE #14: Port math command

### PR DESCRIPTION
**Pull request by Steffan153**
Closes #14

### CODE REVIEW

**Comment by Steffan153** [comment]
Oops it doesn't like the fact that I used Yarn :/

**Comment by Steffan153** [comment]
If I can figure out how to, yeah.

**Comment by johanneslosch** [comment]
For example there There

**Comment by Steffan153** [comment]
But I don't want to remove the changes and then commit, because then when this is merged, the previous PR will be gone. I need so somehow revert the commit, but I can't get it to work.

**Comment by Steffan153** [comment]
So I just delete the changes? In that case, this PR would need to be merged first.

**Comment by johanneslosch** [comment]
> So I just delete the changes? In that case, this PR would need to be merged first.

i mean its possible

**Comment by Steffan153** [comment]
Nvm, I think I wasn't thinking correctly, it should work fine.

**Pull request merged**
